# -*- coding: utf-8 -*-
{
    'name': 'Libreria',
    'version': '1.0',
    'category': 'Academica',
    'description': 'Control de libros',
    'author': 'ADISA',
    'maintainer': 'ADISA',
    'website': 'http://www.itsa.edu.mx',
    'depends': ['base'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/books_view.xml',
        'views/categorys_view.xml',
        'views/editorials_view.xml',
        'views/authors_view.xml',
        'views/students_view.xml',
        'views/careers_view.xml',
        'views/teachers_view.xml',
        'views/prestamos_view.xml',
        'views/menu_view.xml',    
    ],
    'installable': True,
    'auto_install': False,
}